<HomeScreen>:

    MDBoxLayout:
        orientation: "vertical"
        spacing: "15dp"
        padding: "15dp"

        MDTopAppBar:
            title: "Controle de Glicemia"
            elevation: 10

        ScrollView:

            MDList:
                id: glucose_list

        MDRaisedButton:
            text: "Adicionar"
            pos_hint: {"center_x": .5}
            on_release:
                app.root.current = "add"

        MDRaisedButton:
            text: "Gerar Relatório"
            icon: "file-excel-outline"
            on_release: app.salvar_relatorio()