name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite rodar manualmente pelo painel do GitHub

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Android Build-Tools 34
        run: |
          # Define o caminho do executável do sdkmanager
          SDK_MANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
          
          # Aceita as licenças
          yes | $SDK_MANAGER --sdk_root=$ANDROID_HOME --licenses || true
          
          # Instala as ferramentas necessárias usando o caminho completo
          $SDK_MANAGER --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platforms;android-34" "platform-tools"
          
          # Adiciona as ferramentas ao PATH para o Buildozer encontrá-las
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Accept Android SDK Licenses
        run: |
          yes | sdkmanager --licenses || true
          # Força a instalação de uma versão estável dos build-tools
          sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"

      # 1. Instalar dependências do sistema necessárias para o Buildozer
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      # 2. Adicionar o caminho do Buildozer ao PATH do sistema
      - name: Add Buildozer to PATH
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      # 3. Rodar o Buildozer
      - name: Build with Buildozer
        run: buildozer android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: 1
       

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk


      
